common:
    lid_topic:  "/quadrotor/os_cloud_node/points" # "/os_cloud_node/points" # convert ouster_driver::PacketMsg --> sensor_msgs::PointCloud2
    imu_topic:  "/quadrotor/os_cloud_node/imu"  # "/os_cloud_node/imu" # convert ouster_driver::PacketMsg --> sensor_msgs::Imu
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    

# if the two preprocess params are set as point_filter_num: 1 and blind: 0, all points in the raw scan will be kept
point_filter_num: 1 # preprocess param 1: only keep 1 point out of point_filter_num points (as one of preprocessing steps)
preprocess:
    lidar_type: 3                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    vertical_resolution: 64
    horizontal_resolution: 1024
    blind: 0.5 # preprocess param 2: the points having range smaller than blind will be ignored
    time_scale: 1e-3


mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     150.0
    extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic
    extrinsic_T: [ 0.0, 0.0, 0.0 ]
    extrinsic_R: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]

publish:
    path_publish_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    scan_effect_pub_en: true    # true: publish the pointscloud of effect point
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

path_save_en: false

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
feature_extract_enable: false
max_iteration: 3
filter_size_surf: 0.1
filter_size_map: 0.5      # not used in the coee
cube_side_length: 1000

ivox_grid_resolution: 0.5        # default=0.2
ivox_nearby_type: 18             # 6, 18, 26
esti_plane_threshold: 0.1        # default=0.1
